# Generated by Django 3.2 on 2022-05-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_rename_bithdate_doctor_birthdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Diplomas',
            new_name='diplomas',
        ),
    ]
